[workspace]
authors = ["jdtorres <jd.torres1595@gmail.com>"]
channels = ["conda-forge"]
name = "pareto_front"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.13.*"
pymoo = ">=0.6.1.3,<0.7"
matplotlib = ">=3.10.3,<4"
numpy = ">=2.2.6,<3"
scipy = ">=1.15.2,<2"
ipykernel = ">=6.29.5,<7"
